name: Run Test Cases

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Download Go modules
        run: go mod download

      - name: Run tests
        run: |
          for d in [0-9]*; do
            cd $d;
            go test .;
            cd - > /dev/null;
          done
