name: Test LeetCode solutions

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          check-latest: true
          cache: true

      - name: Run tests
        run: go test ./...
